add example: pachyderm-beginner-tutorial in Japanese
opst/knitfab-docs pull request #12
Opened 2024-12-03 01:14 UTC by takaoka-youta-opst

## About This PR

Add a new example based on Pachyderm Begginer Tutorial in Japanese.

To read it in a formatted page, visit https://github.com/takaoka-youta-opst/knitfab-docs/blob/feature/%2311/pachyderm-beginner-tutorial/04.examples/pachyderm-beginner-tutorial/pachyderm-beginner-tutorial.ja.md

2024-12-10 05:40 UTC, hideo-terada-opst reviewed
本件、Pachyderm のチュートリアルを”参考にして”作ろうということでしが、そのことを直接本書に明記するとは思っていませんでした。一応競合製品なので、Pachydermに言及しながら話を展開することはしたくないと思っています。
よって、Pachydermの話を削った形で再構成できないでしょうか。

2024-12-10 05:47 UTC, takaoka-youta-opst commented
そういうことであれば、大幅な再構成が必要ですね。

特に、画像処理タスクのコンテナイメージについては Pachyderm の成果に依存してしまっているので、似たようなものを作りましょう、というところから実装と議論を組み直すことになります。（コンテナイメージのみ拝借して、本文に Pachyderm が出てこない、というのもバランスが取れません）

2025-01-14 07:37 UTC, hideo-terada-opst approved these changes

2025-01-14 07:42 UTC, hideo-terada-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +これによって、以後の `knit data push` や `knit plan template` が、常にこの `project:contour-comparing-pipeline` をセットするようになります。
・・・セットするようになります。ーー＞そうなることで、どのようなご利益があるのか？が書いてあるとさらに分かりやすいのでは？

2025-01-14 07:44 UTC, hideo-terada-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +パイプラインを構築し始める前に、パイプライン全体の見通しを立てます。このパイプラインには次のタスクが必要です。
「構築し始める前に」という表現は「構築する前に」ではダメなのでしょうか？「し始める」になにか含意がありますか？

2025-01-14 07:47 UTC, hideo-terada-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +入力データセットを収集して、 Knitfab にアップロードします。
＜修正案＞
入力データセットをKnitfabにアップロードします。
Knitfabへの入出力はフォルダ毎なので、複数の入力ファイルを一つのフォルダに集めてアップロードします。

2025-01-14 07:47 UTC, hideo-terada-opst commented on 04.examples/comparing-contours/comparing-contours.en.md
> +パイプラインの生成物を確認します。
日本語になってます。

2025-01-14 15:56 UTC, hideo-terada-opst requested changes
気になる点、修正案をコメントしました。

2025-01-14 15:56 UTC, hideo-terada-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +
＜追記案＞
パイプラインとは、いくつかのタスク（処理）が意味のある順序に沿って並んだものです。パイプの中を流れる液体のように、始点から終点までデータが流れていき、その過程で各タスクが順次実行されていくため、パイプラインと呼びます。

Knitfabのパイプラインも、一連の（１つまたは複数の）タスクとして実行します。個々のタスクはPlanによってユーザが定義します。ある１つのタスクが完了すると、Planで決めた規則に従って次のタスクがKnitfabによって起動されます。つまり、ユーザがやるべきことは、個々のタスクの内容と、それらの間をつなぐ規則を考えてPlanを定義していくことです。

2025-01-15 00:46 UTC, takaoka-youta-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +パイプラインを構築し始める前に、パイプライン全体の見通しを立てます。このパイプラインには次のタスクが必要です。
いや、とくにありません。

余計な単語を削って、「する前に」にしましょう。

2025-01-15 00:53 UTC, takaoka-youta-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +パイプラインを構築し始める前に、パイプライン全体の見通しを立てます。このパイプラインには次のタスクが必要です。
```suggestion
パイプラインを構築する前に、パイプライン全体の見通しを立てます。このパイプラインには次のタスクが必要です。
```

2025-01-15 00:55 UTC, takaoka-youta-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +入力データセットを収集して、 Knitfab にアップロードします。
これは「なぜ個別ファイルをアップロートするのではなく、フォルダとしてアップロードするのか」という想定質問に対する回答ですね？

であれば、挿入位置はそこではなくて、56行目

> その後、フォルダ `./raw_videos_and_images` を Knitfab の Data としてアップロードします。

の後に持ってきましょう。

2025-01-15 01:01 UTC, takaoka-youta-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +入力データセットを収集して、 Knitfab にアップロードします。
いや、違うか。
いきなりアップロードするのではなくて、一旦フォルダに集める理由を述べたもの、ですね。

であれば、挿入位置は @hideo-terada-opst のコメントの位置がいいですね。

こうしましょう。

```suggestion
入力データセットを収集して、 Knitfab にアップロードします。
Knitfab では、Data をフォルダ単位で取り扱うので、データセットを収集する段階からファイルをひとつのフォルダにまとめておきます。
```

2025-01-15 02:05 UTC, takaoka-youta-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +これによって、以後の `knit data push` や `knit plan template` が、常にこの `project:contour-comparing-pipeline` をセットするようになります。
なるほど、そうですね。

```suggestion
これによって、以後の `knit data push` や `knit plan template` が、常にこの `project:contour-comparing-pipeline` タグをセットするようになり、他のプロジェクトとこの一連の実験を分離できます。
```

2025-01-15 02:07 UTC, takaoka-youta-opst commented on 04.examples/comparing-contours/comparing-contours.en.md
> +パイプラインの生成物を確認します。
```suggestion
Verify the results generated by the pipeline,
```

2025-01-15 02:11 UTC, takaoka-youta-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +
これは、次の行の内容

> Knitfab にとって「パイプラインを構築する」とは、 Plan を定義してゆくことに他なりません。

を噛み砕いて、「パイプライン」という語の定義を与えつつ、開いたものですね。
であれば、変更範囲には次の行も含めることにしましょう。

2025-01-15 02:13 UTC, takaoka-youta-opst commented on 04.examples/comparing-contours/comparing-contours.ja.md
> +Knitfab にとって「パイプラインを構築する」とは、 Plan を定義してゆくことに他なりません。
```suggestion
パイプラインとは、いくつかのタスク (処理) が意味のある順序に沿って並んだものです。パイプの中を流れる液体のように、始点から終点までデータが流れていき、その過程で各タスクが順次実行されていくため、パイプラインと呼びます。

Knitfab のパイプラインも、一連の (1 つまたは複数の) タスクとして実行します。個々のタスクの定義は、ユーザが Plan として与えます。ある 1 つのタスクが完了すると、Plan で決めた規則に従って次のタスクが Knitfab によって起動されます。つまり、パイプラインを構築するためにユーザがやるべきことは、個々のタスクの内容と、それらの間をつなぐ規則を考えて Plan を定義していくことです。
```

2025-01-15 08:26 UTC, hideo-terada-opst approved these changes

2025-01-15 08:27 UTC, merged